[tool.common_py]
module-dir="vulcan"
application_entry_points = [  # WIP, not yet working
    "vulcan=vulcan.test_ep:main"
]


[tool.poetry]
name = "vulcan"
version = "0.1.0"
description = ""
authors = ["Me"]
packages = [
    { include="vulcan" },
]


[tool.poetry.scripts]
myep = "vulcan.test_ep:main" 

[tool.poetry.dependencies]
python = ">=3.6"
setuptools = "^51.0.0"

[[tool.poetry.source]]
name = "optiver"
url = "http://artifactory.ams.optiver.com/artifactory/api/pypi/pypi/simple"
default = true

[tool.poetry.dev-dependencies]
[build-system]
pytest = "^3.4"
requires=['setuptools']
build-backend="vulcan.build_backend"
backend-path=["."]
