[tool.common_py]
module-dir="testbackend"
application_entry_points = [  # WIP, not yet working
    "testbackendep=testbackend.test_ep:main"
]


[tool.poetry]
name = "testbackend"
version = "0.1.0"
description = ""
authors = ["Me"]
# packages = [
#     { include="testbackend" },
# ]


[tool.poetry.scripts]
myep = "testbackend.test_ep:main"

[tool.poetry.plugins."housekeeper_checks"]
my_test_check="housekeeper_checks.fake.whatever:run_check"
another_test_check="housekeeper_checks.another.check:run_check"

[tool.poetry.dependencies]
python = ">=3.6"
requests = "^2.25.1"

[[tool.poetry.source]]
name = "optiver"
url = "http://artifactory.ams.optiver.com/artifactory/api/pypi/pypi/simple"
default = true

[tool.poetry.dev-dependencies]
[build-system]
pytest = "^3.4"
requires=['setuptools']
build-backend="testbackend"
backend-path=["."]
