[tool.vulcan]
name = "vulcan"
description = "Tool for leveraging poetry lockfiles to pin dependencies in wheels and sdists"
author = "Joel Christiansen"
author_email =  "joelchristiansen@optiver.com"
url = "http://stash.ams.optiver.com/users/joelchristiansen/repos/vulcan/browse"
packages = [ "vulcan" ]
readme = "README.md"
keywords = [ "build", "tooling" ] 
classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
python_requires = ">=3.6"
no-lock = true

[tool.vulcan.entry_points.console_scripts]
vulcan="vulcan.cli:main"

# there is no point in a vulcan shiv application really, although you _can_ throw it in ~/.local/bin if you
# really want to
[[tool.vulcan.shiv]]
bin_name="vulcan"
console_script="vulcan"
interpreter="/usr/bin/env python3.6"
extra_args="-E --compile-pyc"

# there's definitely no point to a second vulcan shiv application that is literally identical to the first,
# this is here only to show that you can configure multiple shiv applications to be built
[[tool.vulcan.shiv]]
bin_name="vulcan2"
entry_point="vulcan.cli:main"
interpreter="/usr/bin/env python3.6"
extra_args="-E --compile-pyc"

# e.g. if these are specified, like `pip install vulcan[cli]
[tool.vulcan.extras]
cli=["shiv~=0.1.0","build[virtualenv]~=0.3.0"]

[tool.vulcan.dependencies]
toml='~=0.10'
setuptools='~=53.0.0'
wheel='~=0.36.2'
dataclasses='~=0.8'
typing_extensions='~=3.7'


[build-system]
# in other build systems, this would says "requires=['setuptools', 'vulcan']" and that is all that is needed
# to correctly install and use this tool
requires=['setuptools', 'toml', 'dataclasses', 'wheel', 'typing_extensions']
build-backend="vulcan.build_backend"
backend-path=["."]  # and this line should be removed for all other projects

[tool.pytest.ini_options]
filterwarnings = [ "ignore:.*the imp module is deprecated in favour of importl.*:DeprecationWarning" ]
junit_family="xunit1"
testpaths = [ "tests", ]
markers = [ 
    "cli: Tests that require full cli dependencies" 
]
