[tool.common_py]
module-dir="testbackend"
application_entry_points = [  # WIP, not yet working
    "testbackendep=testbackend.test_ep:main"
]


[tool.poetry]
name = "testfrontend"
version = "0.1.0"
description = ""
authors = ["Me"]

[tool.poetry.dependencies]
python = ">=3.6"
requests = "^2.25.1"

[[tool.poetry.source]]
name = "optiver"
url = "http://artifactory.ams.optiver.com/artifactory/api/pypi/pypi/simple"
default = true

[tool.poetry.dev-dependencies]
[build-system]
pytest = "^3.4"
requires=['setuptools']
build-backend="testbackend"
backend-path=["."]
